name: Deploy Symfony 7 site

on:
  push:
    branches:
      - main # Déploiement lors d'un push sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code source depuis un dépôt privé
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Étape 2 : Déployer sur le serveur via SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd web
            git pull origin main
            /usr/bin/php8.3 /usr/local/bin/composer install --no-interaction --prefer-dist --optimize-autoloader
            /usr/bin/php8.3 web/bin/console cache:clear --env=prod
            /usr/bin/php8.3 web/bin/console doctrine:migrations:migrate --no-interaction # Si applicable
            /usr/bin/php8.3 web/console assets:install public # Si applicable
