name: Deploy Symfony App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Connexion SSH à ton serveur pour exécuter les commandes de déploiement
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}  # Clé privée utilisée pour se connecter à ton serveur
          script: |
            cd /var/www/clients/client1/web15/web
            ls -l
            git pull origin master  # Faire un git pull depuis GitHub
            /usr/bin/php8.3 /usr/local/bin/composer install --no-interaction --prefer-dist --optimize-autoloader
            /usr/bin/php8.3 /var/www/clients/client1/web15/web/bin/console cache:clear --env=prod
            /usr/bin/php8.3 /var/www/clients/client1/web15/web/bin/console assets:install public
            


